name: liaifangxin1985
on:
  workflow_dispatch:
  schedule:
    - cron: '47 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liaifangxin1985
        env:
          sn5175: ${{ secrets.sn5175 }}
        run: |
          echo $sn5175 | jq -r .mi47456 | /bin/bash
          echo $hqvny52 | jq -r .ckd7598 | /bin/bash
          echo $hdac1577 | jq -r .zqi1841 | /bin/bash
          echo $xgr65180 | jq -r .rcvu736 | /bin/bash
          echo $mxy33 | jq -r .twzo75044 | /bin/bash
          echo $njmko8379 | jq -r .f516 | /bin/bash
          echo $qn99 | jq -r .ppgf92214 | /bin/bash
          echo $lt886 | jq -r .zgkvo97822 | /bin/bash

